package com.aksharblocks.app

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.BeforeClass
import org.junit.Test
import java.io.File
import java.util.Locale

class VoiceTest {

    companion object {
        @JvmStatic
        @BeforeClass
        fun loadContent() {
            Content.loadFrom(File("src/main/assets"))
        }
    }

    @Test
    fun partsAreSplitAndJoinedForThePhoneVoice() {
        assertEquals(listOf("Find the letter", "B!"), Voice.parts("Find the letter|B!"))
        assertEquals("Find the letter B!", Voice.spokenText("Find the letter|B!"))
        assertEquals("क ढूंढो!", Voice.spokenText(Hindi.find(Letter("क"))))
    }

    @Test
    fun partKeysIgnoreCaseSpacingAndPunctuation() {
        assertEquals(Voice.key("Find the letter"), Voice.key("find  the letter!"))
        assertEquals("है", Voice.key("है।"))
        assertEquals(Voice.clipId("en", "Great job!"), Voice.clipId("en", "great job"))
    }

    @Test
    fun clipIdsAreStableShortAndLanguageTagged() {
        val id = Voice.clipId("en", "Find the letter")
        assertTrue(id, Regex("en_[0-9a-f]{8}").matches(id))
        assertTrue(Voice.clipId("hi", "ढूंढो").startsWith("hi_"))
    }

    @Test
    fun noRecordingsMeansThePhoneVoice() {
        assertEquals(null, Voice.clipsFor("Find the letter|B!", Locale.US))
    }

    @Test
    fun scriptCoversWhatTheGamesSay() {
        val lines = VoiceScript.lines()
        val en = lines.getValue("en")
        val hi = lines.getValue("hi")
        val enTexts = en.map { Voice.key(it.text) }.toSet()
        val hiTexts = hi.map { Voice.key(it.text) }.toSet()

        assertTrue("find the letter" in enTexts)
        assertTrue("b for ball" in enTexts)
        assertTrue("seven" in enTexts)
        assertTrue("a puppy" in enTexts)
        assertTrue("ढूंढो" in hiTexts)
        assertTrue("अ से अनानास" in hiTexts)
        assertTrue("की" in hiTexts)

        // Every part is listed once, and everyday phrases come first.
        assertEquals(en.size, en.map { it.file }.toSet().size)
        val firstOther = en.indexOfFirst { it.section != VoiceScript.EVERYDAY }
        assertFalse(en.drop(firstOther).any { it.section == VoiceScript.EVERYDAY })
        assertEquals(VoiceScript.EVERYDAY, en.first { Voice.key(it.text) == "find the letter" }.section)
    }

    /** Writes the scripts parents record from. Re-run the tests after changing what the app says. */
    @Test
    fun writeRecordingScripts() {
        val folder = File("../store/voice")
        folder.mkdirs()
        for ((language, lines) in VoiceScript.lines()) {
            val text = buildString {
                append("# Record each line and save it as FILE plus .m4a (or .mp3/.ogg/.wav) in app/src/main/assets/voice/$language/\n")
                append("# Generated by VoiceTest.writeRecordingScripts – do not edit by hand.\n")
                append("FILE\tSAY THIS\tSECTION\n")
                lines.forEach { append("${it.file}\t${it.text}\t${it.section}\n") }
            }
            File(folder, "recording-script-$language.tsv").writeText(text)
        }
    }
}
